databak/testcase_CRM.yaml:
- CRM系统_系统管理_获取销售登录人的部门机构信息
- CRM系统_系统管理_获取财务登录人的部门机构信息
- CRM系统_系统管理_获取法务登录人的部门机构信息
- CRM系统_系统管理_获取交付登录人的部门机构信息
- CRM系统_合同管理_销售人员上传合同
- CRM系统_合同管理_销售人员新建合同保存
- CRM系统_合同管理_获取新建合同ID
- CRM系统_合同管理_修改合同
- CRM系统_合同管理_无风险合同提交审批
- CRM系统_合同管理_财务提交审批
- CRM系统_合同管理_法务提交审批
- CRM系统_合同管理_交付提交审批
- CRM系统_合同管理_销售提交审批到流程引擎
- CRM系统_合同管理_销售人员新建有风险合同保存
- CRM系统_合同管理_获取新建有风险合同ID
- CRM系统_合同管理_修改有风险合同
- CRM系统_合同管理_有风险合同提交审批
- CRM系统_合同管理_获取风险基准组ID
- CRM系统_合同管理_获取风险ID
- CRM系统_线索管理_获取适用OU
- CRM系统_客户管理_新建企业库
- CRM系统_客户管理_添加联系人
- CRM系统_客户管理_客户建档
- CRM系统_商机管理_获取商机编码
- CRM系统_商机管理_获取商机规则ID
- CRM系统_合同管理_查询客户信息
- CRM系统_客户管理_查询已发布的版本库
- CRM系统_客户管理_查询复制版本库ID
- CRM系统_客户管理_产品库新增客户
- CRM系统_客户管理_产品库发布
- CRM系统_市场管理_授权类别
- CRM系统_市场管理_查询全部资讯
- CRM系统_市场管理_获取类别详情
- CRM系统_市场管理_上传封面
- CRM系统_市场管理_发布管理暂存
- CRM系统_市场管理_查询资讯ID
- CRM系统_市场管理_删除资讯
- CRM系统_市场管理_发布资讯
- CRM系统_市场管理_复制资讯
- CRM系统_市场管理_查询复制资讯信息
- CRM系统_客户管理_查询所有企业
- CRM系统_客户管理_查询所有联系人
- CRM系统_客户管理_查询所有客户建档
- CRM系统_线索管理_选择客户
- CRM系统_线索管理_添加客户联系人
- CRM系统_线索管理_获取产品库ID
- CRM系统_线索管理_新增产品库
- CRM系统_线索管理_获取客户联系人
- CRM系统_线索管理_保存线索
- CRM系统_线索管理_领取线索
- CRM系统_线索管理_添加跟进记录
- CRM系统_线索管理_添加跟进任务
- CRM系统_线索管理_释放公海池
- CRM系统_线索管理_再次领取线索
- CRM系统_线索管理_线索失效
databak/testcase_Meet.yaml:
- MEET系统_会务管理_获取登录账号Id
- MEET系统_会务管理_会议室查询
- MEET系统_会务管理_账单查询
databak/testcase_OTD.yaml:
- OTD系统_订单管理_新增订单yaml
- OTD系统_订单管理_新增行信息yaml
- OTD系统_订单管理_校验与匹配yaml
- OTD系统_订单管理_启动审批yaml
databak/testcase_SRM.yaml:
- SRM系统_合同管理_技术协议查询yaml
databak/apply.yaml:
- CRM系统_报价管理_获取报价申请单号
- CRM系统_报价管理_报价申请单提交
databak/test.yaml:
- CRM系统_报价管理_获取报价申请单号
- CRM系统_报价管理_报价申请单提交
databak/testcase_MRO.yaml:
- MRO系统_订单管理_查询订单列表
