Authorization: bearer a2082fbd-a242-488c-8d36-f2d21ec3fee3
Deptid: '1736985558099075099'
Orgid: '1685834481767059497'
email: ming43@hotmail.com
phone: '15267310655'
contactsName: 范玉梅
customerName: 中国三六重工91430分公司
orgName: 欣智旺
deptName: 销售二部
contractName: 合同03090
loginurl: https://crm-uat.sunwoda.com/login/
starttime: '2024-12-09 09:05:34'
datetimelist:
  date_yesterday: '2024-12-08'
  date_today: '2024-12-09'
  time_today: '2024-12-09 09:05:34'
  date_tomorrow: '2024-12-10'
  yesterday_timestamp: '1733587200'
  current_timestamp: '1733673600'
  tomorrow_timestamp: '1733760000'
  begin_data_last_month: '2024-11-01'
  end_data_last_month: '2024-11-30'
  begin_data_current_month: '2024-12-01'
  end_data_current_month: '2024-12-31'
  begin_data_next_month: '2025-01-01'
  end_data_next_month: '2025-01-31'
  last_month: '11'
  current_month: '12'
  next_month: '01'
  last_year: '2023'
  current_year: '2024'
  next_year: '2025'
  begin_crrent_weekday: '2024-12-09'
  end_crrent_weekday: '2024-12-15'
  begin_last_weekday: '2024-12-02'
  end_last_weekday: '2024-12-08'
  begin_data_current_year: '2024-01-01'
  end_data_current_year: '2024-12-31'
  begin_data_last_year: '2023-01-01'
  end_data_last_year: '2023-12-31'
  randmun: 2810A0D25F55
  datetimename: '20241209090534'
  datatoday: 09
  randintdata: '90559'
